name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.0.0
      - run: npm install
      - run: CI=false npm run build