name: Deploy

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.0.0

      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
            ENV_VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
            ENV_VITE_BACKEND_BASE_URL: ${{ secrets.VITE_BACKEND_BASE_URL }}

      - name: SEE ENV FILE
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          echo | cat .env

      - name: install-dependencies-and-build
        run: |
          npm install
          CI=false npm run build

      - name: deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: dist/*
          target: /var/www/projectmanager/html
          rm: true