name: Deploy

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.0.0

      - name: Crete env file
        env:
          VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
          VITE_BACKEND_BASE_URL: ${{ secrets.VITE_BACKEND_BASE_URL }}
        run: |
          rm -r .env
          touch .env
          echo $VITE_CLERK_PUBLISHABLE_KEY >> .env
          echo $VITE_BACKEND_BASE_URL >> .env

      - name: install-dependencies-and-build
        run: |
          npm install
          CI=false npm run build

      - name: deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: dist/*
          target: /var/www/projectmanager/html
          rm: true